-- Pass the current library as the first argument. Writes/deletes only its own unique test profile.
local Hutame = ...
assert(Hutame, "Pass the library to this test")
local HttpService = game:GetService("HttpService")
local window = Hutame:CreateWindow({ Title = "Feature tests", AnimationDuration = 0.08, ConfigFolder = "HutameUI_Tests" })
local profileName = "test_" .. HttpService:GenerateGUID(false):gsub("-", "")
local profileWritten = false
local ok, result = pcall(function()
    local tab = window:CreateTab("Controls")
    local section = tab:CreateSection("Controls")
    local other = window:CreateTab("Other"):CreateSection({Name = "Advanced", Collapsed = true})
    local toggle = section:CreateToggle({ Name = "Enabled", Flag = "test_enabled", Default = false, Tooltip = "Tooltip test" })
    local speed = other:CreateSlider({ Name = "Movement speed", Min = 1, Max = 100, Default = 20, Flag = "test_speed" })
    local changes, activations = 0, 0
    local key = section:CreateKeybind({ Name = "Action shortcut", Flag = "test_key", Default = Enum.KeyCode.F7,
        Changed = function() changes += 1 end, Callback = function() activations += 1 end })
    local key2 = section:CreateKeybind({ Name = "Other shortcut", Flag = "test_key2", Default = Enum.KeyCode.F8 })
    assert(not pcall(function() key:SetValue(Enum.KeyCode.RightControl) end))
    assert(not pcall(function() key:SetValue(Enum.KeyCode.F8) end))
    key:Capture(); window:_handleInput({KeyCode = Enum.KeyCode.Escape}, false)
    assert(window._capturing == nil and key:GetValue() == Enum.KeyCode.F7)
    key:Capture(); window:_handleInput({KeyCode = Enum.KeyCode.F9}, false)
    task.wait()
    assert(key:GetValue() == Enum.KeyCode.F9 and activations == 0 and changes == 1)
    window:_handleInput({KeyCode = Enum.KeyCode.F9}, false); task.wait()
    assert(activations == 1)
    key:SetDisabled(true); window:_handleInput({KeyCode = Enum.KeyCode.F9}, false); task.wait()
    assert(activations == 1); key:SetDisabled(false)
    local runs = 0
    local action = section:CreateButton({ Name = "Primary", Style = "Primary", Compact = true, Callback = function() runs += 1; task.wait(0.15) end })
    action:Activate(); action:Activate()
    assert(action.Loading)
    task.wait(0.25)
    assert(runs == 1 and not action.Loading)
    action:SetDisabled(true); action:Activate(); task.wait()
    assert(runs == 1)
    action:SetLoading(true); action:SetLoading(false)
    assert(action.Disabled, "Loading must preserve disabled state")
    window:SetSize(Vector2.new(1, 1)); assert(window:GetSize() == window.MinSize)
    window:SetSize(UDim2.fromOffset(660, 440)); assert(window:GetSize() == Vector2.new(660, 440))
    window:SetSearch("movement")
    task.wait(0.35)
    assert(window.SelectedTab == other.Tab and speed.Root.Visible and not toggle.Root.Visible)
    assert(other._searchExpanded and other.Root.Size.Y.Offset > 32)
    window:SetSearch("no-such-control")
    assert(window.EmptySearch.Visible)
    window:SetSearch(""); task.wait(0.2)
    assert(not window.EmptySearch.Visible and other.Collapsed and other.Root.Size.Y.Offset == 32)
    other:SetCollapsed(false); task.wait(0.25)
    assert(other.Root.Size.Y.Offset > 32)
    toggle:SetVisible(false); window:SetSearch("Enabled"); assert(not toggle.Root.Visible)
    window:SetSearch(""); toggle:SetVisible(true); tab:Select(); task.wait(0.2)
    firesignal(toggle.Root.MouseEnter); task.wait(0.5)
    assert(window.Tooltip.Visible and window.TooltipText.Text == "Tooltip test")
    firesignal(toggle.Root.MouseLeave); assert(not window.Tooltip.Visible)
    toggle:SetValue(true, true); speed:SetValue(42, true)
    local snapshot = window:ExportConfig()
    toggle:SetValue(false, true); speed:SetValue(10, true)
    assert(window:ImportConfig(snapshot, true))
    assert(toggle:GetValue() == true and speed:GetValue() == 42)
    local malformed = HttpService:JSONDecode(snapshot)
    malformed.values.test_speed.value = "invalid"
    assert(not window:ImportConfig(HttpService:JSONEncode(malformed)))
    assert(speed:GetValue() == 42 and toggle:GetValue() == true, "Invalid config partially applied")
    local swapped = HttpService:JSONDecode(snapshot)
    swapped.values.test_key.value = "F8"; swapped.values.test_key2.value = "F9"
    assert(window:ImportConfig(HttpService:JSONEncode(swapped)))
    task.wait(); assert(activations == 1, "Loading a keybind must not execute its action")
    assert(key:GetValue() == Enum.KeyCode.F8 and key2:GetValue() == Enum.KeyCode.F9)
    assert(window:ResetConfig(true))
    assert(not toggle:GetValue() and speed:GetValue() == 20 and key:GetValue() == Enum.KeyCode.F7)
    assert(not window:SaveConfig("../escape"))
    local saved, saveError = window:SaveConfig(profileName)
    assert(saved, saveError); profileWritten = true
    assert(not window:SaveConfig(profileName), "Existing profile overwritten without permission")
    assert(window:SaveConfig(profileName, true))
    local profiles, profileError = window:ListConfigs()
    assert(not profileError and table.find(profiles, profileName))
    toggle:SetValue(true, true)
    assert(window:LoadConfig(profileName, true)); assert(not toggle:GetValue())
    assert(window:DeleteConfig(profileName)); profileWritten = false
    assert(not window:LoadConfig(profileName))
    window:CreateConfigTab()
    key:Capture(); window:Hide(); assert(window._capturing == nil)
    return "PASS: key capture/conflicts/actions, loading/disabled, sizing, search, collapse, tooltip, transactional config validation, file profiles"
end)
if profileWritten then window:DeleteConfig(profileName) end
window:Destroy()
assert(ok, result)
return result
