import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const library = readFileSync(resolve(root, 'src/init.lua'), 'utf8');
const example = readFileSync(resolve(root, 'examples/DemoHub.client.lua'), 'utf8');
const prelude = 'local Hutame = ...\n';
if (!example.startsWith(prelude)) throw new Error('Demo must accept the library as its first argument');
mkdirSync(resolve(root, 'dist'), { recursive: true });
writeFileSync(resolve(root, 'dist/Hutame.lua'), library);
writeFileSync(resolve(root, 'dist/DemoHub.lua'),
    '-- Generated by scripts/build.mjs. Runs standalone with loadstring.\n' +
    'local Hutame = (function()\n' + library + '\nend)();\n' +
    '(function(...)\n' + example + '\nend)(Hutame)\n');
console.log('Built dist/Hutame.lua and dist/DemoHub.lua');
